python predict.py   --save_txt true \
                    --parse test \
                    --path_save results \
                    --checkpoint_dir checkpoints \
                    --activation linear \
                    --nb_classes 2 \
                    --name_model resnet50 \
                    --num_train 000 \
                    --num_ckpt 1 \
                    --threshold 1 \
                    --resize false \
                    --load_height 224 \
                    --load_width 128 \
                    --pretrained False \
                    --img_input img_face \
                    --batch_size 16 \
                    --num_workers 2 \
                    --combine 000 \
                    # --ycbcr false
